import "dotenv/config";
import mongoose from "mongoose";
import Property from "./src/models/property.model.js";
import User from "./src/models/user.model.js";

const img = (id) =>
    `https://images.unsplash.com/photo-${id}?w=800&auto=format&fit=crop&q=80`;

const pool = {
    exterior: [
        img("1600596542815-ffad4c1539a9"),
        img("1600585154340-be6161a56a0c"),
        img("1512917774080-9991f1c4c750"),
        img("1564013799919-ab600027ffc6"),
        img("1570129477492-45c003edd2be"),
        img("1568605114967-8130f3a36994"),
        img("1583608205776-bfd35f0d9f83"),
    ],
    interior: [
        img("1522708323590-d24dbb6b0267"),
        img("1502672260266-1c1ef2d93688"),
        img("1560448204-e02f11c3d0e2"),
        img("1484154218962-a197022b5858"),
        img("1554995207-c18c203602cb"),
        img("1493809842364-78817add7ffb"),
        img("1600573472591-ee6981cf35b6"),
        img("1600210492493-0946911123ea"),
        img("1600607687939-ce8a6c25118c"),
    ],
    luxury: [
        img("1576941089067-2de3c901e126"),
        img("1600047509807-ba8f99d2cdde"),
        img("1523217582562-09d0def993a6"),
        img("1560185007-cde436f6a4d0"),
    ],
    office: [
        img("1497366216548-37526070297c"),
        img("1497215728526-462cba7b979e"),
        img("1486325212027-8081e485255e"),
    ],
};

// pick 3 images cycling through a pool
const p3 = (arr) => [arr[0], arr[1] || arr[0], arr[2] || arr[0]];

const A = {
    apt: ["Wi-Fi", "Air Conditioning", "Elevator", "Laundry", "Intercom"],
    house: ["Parking", "Garden", "Air Conditioning", "Washer/Dryer", "Storage"],
    villa: ["Private Pool", "Garden", "Parking", "Security", "Air Conditioning", "Home Theater"],
    studio: ["Wi-Fi", "Air Conditioning", "Elevator", "Utilities Included"],
    office: ["High-Speed Internet", "Meeting Rooms", "Parking", "Reception", "Security"],
    shop: ["High Foot Traffic", "Storage Room", "CCTV", "Air Conditioning", "Loading Bay"],
};

const seed = [
    // ── APARTMENTS (12) ──────────────────────────────────────────────────────
    {
        title: "Manhattan Heights Apartment",
        description: "Elegant 2-bedroom apartment in the heart of Manhattan with floor-to-ceiling windows and stunning skyline views. Steps from Central Park and top dining options.",
        location: "Manhattan, New York",
        type: "apartment", rent: 3200, rentType: "monthly",
        bedrooms: 2, bathrooms: 1, size: 850,
        amenities: A.apt,
        images: [pool.interior[0], pool.interior[3], pool.interior[6]],
        extraFeatures: "Skyline views, concierge service",
        status: "approved",
    },
    {
        title: "Brooklyn Riverside Apartment",
        description: "Modern 1-bedroom apartment in trendy Brooklyn with East River views and a shared rooftop terrace. Open-plan living with hardwood floors throughout.",
        location: "Brooklyn, New York",
        type: "apartment", rent: 2600, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 650,
        amenities: ["Wi-Fi", "Rooftop Terrace", "Elevator", "Gym", "Bike Storage"],
        images: [pool.interior[1], pool.interior[4], pool.interior[7]],
        extraFeatures: "Rooftop access, pet-friendly building",
        status: "approved",
    },
    {
        title: "Downtown LA Luxury Apartment",
        description: "Sophisticated 2-bedroom apartment in the LA financial district. Gourmet kitchen, spa-like bathrooms, and a private balcony overlooking the city.",
        location: "Downtown, Los Angeles",
        type: "apartment", rent: 2800, rentType: "monthly",
        bedrooms: 2, bathrooms: 2, size: 980,
        amenities: A.apt,
        images: [pool.interior[2], pool.interior[5], pool.interior[8]],
        extraFeatures: "City views, valet parking available",
        status: "approved",
    },
    {
        title: "Santa Monica Beachside Apartment",
        description: "Sun-drenched 1-bedroom two blocks from Santa Monica Beach. Private balcony, in-unit laundry, and ocean breezes year-round.",
        location: "Santa Monica, Los Angeles",
        type: "apartment", rent: 3500, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 720,
        amenities: ["Wi-Fi", "Balcony", "Air Conditioning", "Laundry", "Parking"],
        images: [pool.interior[0], pool.interior[6], pool.exterior[0]],
        extraFeatures: "Beach access, surfboard storage",
        status: "approved",
    },
    {
        title: "Miami Brickell Highrise",
        description: "Stunning high-rise apartment in Brickell with Biscayne Bay views. Chef's kitchen and access to resort-style amenities including pool and spa.",
        location: "Brickell, Miami",
        type: "apartment", rent: 2400, rentType: "monthly",
        bedrooms: 2, bathrooms: 2, size: 900,
        amenities: ["Pool", "Gym", "Concierge", "Valet Parking", "Spa"],
        images: [pool.interior[1], pool.interior[5], pool.exterior[1]],
        extraFeatures: "Bay views, 24/7 concierge",
        status: "approved",
    },
    {
        title: "Chicago Loop Apartment",
        description: "Contemporary 2-bedroom in the Chicago Loop, steps from Millennium Park. High ceilings, stainless steel appliances, and an exposed brick accent wall.",
        location: "Loop, Chicago",
        type: "apartment", rent: 2100, rentType: "monthly",
        bedrooms: 2, bathrooms: 1, size: 870,
        amenities: A.apt,
        images: [pool.interior[2], pool.interior[4], pool.interior[7]],
        extraFeatures: "Exposed brick, Millennium Park views",
        status: "approved",
    },
    {
        title: "Seattle Capitol Hill Apartment",
        description: "Vibrant 1-bedroom in Capitol Hill, the center of Seattle's arts and dining scene. Hardwood floors, updated kitchen, and a cozy reading nook.",
        location: "Capitol Hill, Seattle",
        type: "apartment", rent: 1800, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 640,
        amenities: ["Wi-Fi", "Air Conditioning", "Laundry", "Storage"],
        images: [pool.interior[3], pool.interior[6], pool.interior[0]],
        extraFeatures: "Walkable neighborhood, coffee shop downstairs",
        status: "approved",
    },
    {
        title: "Boston Back Bay Classic",
        description: "Charming 2-bedroom in a historic Back Bay brownstone. Original moldings with modern updates, private deck, and steps from Newbury Street shopping.",
        location: "Back Bay, Boston",
        type: "apartment", rent: 2900, rentType: "monthly",
        bedrooms: 2, bathrooms: 1, size: 930,
        amenities: ["Wi-Fi", "Laundry", "Storage", "Deck"],
        images: [pool.interior[1], pool.interior[3], pool.interior[8]],
        extraFeatures: "Historic brownstone, private deck",
        status: "approved",
    },
    {
        title: "Austin South Congress Apartment",
        description: "Trendy 1-bedroom on South Congress Avenue with easy access to Austin's best restaurants, boutiques, and live music venues.",
        location: "South Congress, Austin",
        type: "apartment", rent: 1700, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 680,
        amenities: ["Wi-Fi", "Air Conditioning", "Pool", "Gym"],
        images: [pool.interior[4], pool.interior[7], pool.interior[2]],
        extraFeatures: "Community pool, live music nearby",
        status: "approved",
    },
    {
        title: "Denver Highland Apartment",
        description: "Modern 2-bedroom in trendy LoHi with mountain views. Open floor plan, rooftop deck, and walking distance to award-winning restaurants.",
        location: "Highland, Denver",
        type: "apartment", rent: 2000, rentType: "monthly",
        bedrooms: 2, bathrooms: 2, size: 920,
        amenities: ["Wi-Fi", "Rooftop Deck", "Gym", "Parking", "Air Conditioning"],
        images: [pool.interior[5], pool.interior[0], pool.interior[6]],
        extraFeatures: "Mountain views, rooftop deck",
        status: "approved",
    },
    {
        title: "Nashville Gulch Apartment",
        description: "Chic 1-bedroom in The Gulch, Nashville's most walkable neighborhood. Modern finishes, floor-to-ceiling windows, and resort-style pool access.",
        location: "The Gulch, Nashville",
        type: "apartment", rent: 1900, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 700,
        amenities: ["Pool", "Gym", "Concierge", "Wi-Fi", "Air Conditioning"],
        images: [pool.interior[2], pool.interior[7], pool.interior[4]],
        extraFeatures: "Pool views, walkable to restaurants",
        status: "approved",
    },
    {
        title: "Atlanta Midtown Apartment",
        description: "Stylish 2-bedroom in Midtown Atlanta with Piedmont Park views. Open kitchen, in-unit washer/dryer, and access to a rooftop lounge.",
        location: "Midtown, Atlanta",
        type: "apartment", rent: 2200, rentType: "monthly",
        bedrooms: 2, bathrooms: 2, size: 880,
        amenities: ["Wi-Fi", "Rooftop Lounge", "Gym", "Washer/Dryer", "Parking"],
        images: [pool.interior[3], pool.interior[8], pool.interior[5]],
        extraFeatures: "Park views, rooftop lounge access",
        status: "approved",
    },

    // ── HOUSES (12) ──────────────────────────────────────────────────────────
    {
        title: "Brooklyn Family Townhouse",
        description: "Spacious 4-bedroom Brooklyn townhouse with a private backyard and finished basement. Renovated kitchen, original hardwood floors, and a two-car parking pad.",
        location: "Park Slope, Brooklyn",
        type: "house", rent: 5800, rentType: "monthly",
        bedrooms: 4, bathrooms: 2, size: 2100,
        amenities: A.house,
        images: p3(pool.exterior),
        extraFeatures: "Private backyard, finished basement",
        status: "approved",
    },
    {
        title: "Silver Lake Craftsman Home",
        description: "Gorgeous 3-bedroom craftsman bungalow with original character details. Updated kitchen, sunny backyard with fruit trees, and a detached studio.",
        location: "Silver Lake, Los Angeles",
        type: "house", rent: 4800, rentType: "monthly",
        bedrooms: 3, bathrooms: 2, size: 1650,
        amenities: A.house,
        images: [pool.exterior[1], pool.exterior[3], pool.exterior[5]],
        extraFeatures: "Detached studio, fruit trees in yard",
        status: "approved",
    },
    {
        title: "Coral Gables Family Home",
        description: "Beautiful 4-bedroom home in prestigious Coral Gables, steps from the Venetian Pool. Private pool, lush garden, and two-car garage.",
        location: "Coral Gables, Miami",
        type: "house", rent: 5200, rentType: "monthly",
        bedrooms: 4, bathrooms: 3, size: 2400,
        amenities: ["Private Pool", "Garage", "Garden", "Air Conditioning", "Security"],
        images: [pool.exterior[0], pool.exterior[2], pool.exterior[4]],
        extraFeatures: "Private pool, gated community",
        status: "approved",
    },
    {
        title: "Lincoln Park Chicago House",
        description: "Elegant 3-bedroom home on a tree-lined street in Lincoln Park. Gourmet kitchen, master suite with walk-in closet, and a private deck.",
        location: "Lincoln Park, Chicago",
        type: "house", rent: 4200, rentType: "monthly",
        bedrooms: 3, bathrooms: 2, size: 1900,
        amenities: A.house,
        images: [pool.exterior[1], pool.exterior[4], pool.exterior[6]],
        extraFeatures: "Two-car garage, private deck",
        status: "approved",
    },
    {
        title: "Bellevue Modern Family Home",
        description: "Contemporary 4-bedroom home in Bellevue with Cascade Mountain views. Open-plan living, smart home features, and a spacious three-car garage.",
        location: "Bellevue, Seattle",
        type: "house", rent: 4500, rentType: "monthly",
        bedrooms: 4, bathrooms: 3, size: 2600,
        amenities: ["Smart Home", "Garage", "Garden", "Air Conditioning", "Washer/Dryer"],
        images: [pool.exterior[2], pool.exterior[5], pool.exterior[6]],
        extraFeatures: "Mountain views, smart home system",
        status: "approved",
    },
    {
        title: "Newton Colonial Home",
        description: "Charming 3-bedroom colonial in Newton with a generous backyard. Top-rated school access, updated kitchen, and easy T access into Boston.",
        location: "Newton, Boston",
        type: "house", rent: 4900, rentType: "monthly",
        bedrooms: 3, bathrooms: 2, size: 1800,
        amenities: A.house,
        images: [pool.exterior[0], pool.exterior[3], pool.exterior[6]],
        extraFeatures: "Top school district, large backyard",
        status: "approved",
    },
    {
        title: "Westlake Hills Home",
        description: "Stunning 4-bedroom home with Hill Country views. Infinity pool, outdoor kitchen, and an open-plan layout perfect for entertaining.",
        location: "Westlake Hills, Austin",
        type: "house", rent: 5500, rentType: "monthly",
        bedrooms: 4, bathrooms: 3, size: 2800,
        amenities: ["Infinity Pool", "Outdoor Kitchen", "Garden", "Garage", "Air Conditioning"],
        images: [pool.exterior[1], pool.exterior[4], pool.exterior[6]],
        extraFeatures: "Hill Country views, infinity pool",
        status: "approved",
    },
    {
        title: "Cherry Creek Tudor Home",
        description: "Exquisite 3-bedroom Tudor in Cherry Creek North, steps from boutiques and restaurants. Renovated kitchen, private courtyard, and two-car garage.",
        location: "Cherry Creek, Denver",
        type: "house", rent: 4100, rentType: "monthly",
        bedrooms: 3, bathrooms: 2, size: 1750,
        amenities: A.house,
        images: [pool.exterior[2], pool.exterior[5], pool.exterior[6]],
        extraFeatures: "Courtyard garden, walkable neighborhood",
        status: "approved",
    },
    {
        title: "East Nashville Bungalow",
        description: "Charming 2-bedroom 1920s bungalow in Five Points, walking distance to East Nashville's best bars, coffee shops, and vintage stores.",
        location: "East Nashville, Tennessee",
        type: "house", rent: 2800, rentType: "monthly",
        bedrooms: 2, bathrooms: 1, size: 1100,
        amenities: ["Garden", "Washer/Dryer", "Parking", "Wi-Fi"],
        images: [pool.exterior[0], pool.exterior[3], pool.exterior[5]],
        extraFeatures: "Covered front porch, original hardwood",
        status: "approved",
    },
    {
        title: "Portland Heights Craftsman",
        description: "Beautiful 3-bedroom craftsman home with city and Cascade views. Wraparound porch, updated kitchen, and a terraced garden with fruit trees.",
        location: "Portland Heights, Oregon",
        type: "house", rent: 3400, rentType: "monthly",
        bedrooms: 3, bathrooms: 2, size: 1650,
        amenities: A.house,
        images: [pool.exterior[1], pool.exterior[4], pool.exterior[6]],
        extraFeatures: "City views, wraparound porch",
        status: "approved",
    },
    {
        title: "Buckhead Classic Home",
        description: "Traditional 4-bedroom home in prestigious Buckhead. Formal dining, gourmet kitchen, screened-in porch, and beautifully landscaped yard.",
        location: "Buckhead, Atlanta",
        type: "house", rent: 3800, rentType: "monthly",
        bedrooms: 4, bathrooms: 3, size: 2200,
        amenities: ["Garden", "Garage", "Screened Porch", "Air Conditioning", "Washer/Dryer"],
        images: [pool.exterior[2], pool.exterior[4], pool.exterior[6]],
        extraFeatures: "Screened porch, landscaped yard",
        status: "approved",
    },
    {
        title: "Scottsdale Desert Home",
        description: "Desert-inspired 3-bedroom home with mountain views. Heated pool, outdoor entertaining area with grill, and designer interiors throughout.",
        location: "Scottsdale, Arizona",
        type: "house", rent: 3200, rentType: "monthly",
        bedrooms: 3, bathrooms: 2, size: 1900,
        amenities: ["Heated Pool", "Outdoor Grill", "Garage", "Air Conditioning"],
        images: [pool.exterior[0], pool.exterior[2], pool.exterior[5]],
        extraFeatures: "Heated pool, mountain views",
        status: "approved",
    },

    // ── VILLAS (8) ───────────────────────────────────────────────────────────
    {
        title: "Beverly Hills Grand Villa",
        description: "Iconic 5-bedroom Beverly Hills villa with panoramic city-to-ocean views. Infinity pool, home theater, wine cellar, private gym, and full staff quarters.",
        location: "Beverly Hills, Los Angeles",
        type: "villa", rent: 15000, rentType: "monthly",
        bedrooms: 5, bathrooms: 5, size: 6500,
        amenities: A.villa,
        images: p3(pool.luxury),
        extraFeatures: "Infinity pool, home theater, wine cellar",
        status: "approved",
    },
    {
        title: "Miami Beach Waterfront Villa",
        description: "Breathtaking 4-bedroom villa on Miami Beach with private dock and direct ocean access. Chef's kitchen, outdoor pool, and 360-degree water views.",
        location: "Miami Beach, Florida",
        type: "villa", rent: 12000, rentType: "monthly",
        bedrooms: 4, bathrooms: 4, size: 4800,
        amenities: ["Private Dock", "Pool", "Outdoor Kitchen", "Security", "Home Automation"],
        images: [pool.luxury[0], pool.luxury[2], pool.exterior[0]],
        extraFeatures: "Private dock, ocean access",
        status: "approved",
    },
    {
        title: "Malibu Clifftop Villa",
        description: "Dramatic clifftop 4-bedroom villa in Malibu with uninterrupted Pacific Ocean views. Infinity pool that appears to merge with the sea and a private beach path.",
        location: "Malibu, California",
        type: "villa", rent: 18000, rentType: "monthly",
        bedrooms: 4, bathrooms: 4, size: 5200,
        amenities: A.villa,
        images: [pool.luxury[1], pool.luxury[3], pool.exterior[1]],
        extraFeatures: "Clifftop infinity pool, private beach path",
        status: "approved",
    },
    {
        title: "Palm Beach Estate",
        description: "Classic 5-bedroom Palm Beach estate with tropical gardens and a lagoon-style pool. Tennis court, guest house, and steps from Worth Avenue shopping.",
        location: "Palm Beach, Florida",
        type: "villa", rent: 10000, rentType: "monthly",
        bedrooms: 5, bathrooms: 5, size: 5800,
        amenities: ["Tennis Court", "Lagoon Pool", "Guest House", "Garden", "Security"],
        images: [pool.luxury[0], pool.luxury[3], pool.exterior[2]],
        extraFeatures: "Tennis court, guest house",
        status: "approved",
    },
    {
        title: "Scottsdale Desert Villa",
        description: "Award-winning desert contemporary villa on a private golf course. Negative-edge pool, outdoor fireplace, and floor-to-ceiling retractable walls.",
        location: "Paradise Valley, Scottsdale",
        type: "villa", rent: 8500, rentType: "monthly",
        bedrooms: 4, bathrooms: 4, size: 4200,
        amenities: ["Negative Edge Pool", "Golf Course Access", "Outdoor Fireplace", "Smart Home", "Security"],
        images: [pool.luxury[1], pool.luxury[2], pool.exterior[3]],
        extraFeatures: "Golf course views, retractable walls",
        status: "approved",
    },
    {
        title: "Austin Hill Country Villa",
        description: "Spectacular 5-bedroom Texas Hill Country villa with panoramic rolling views. Infinity pool, outdoor entertainment pavilion, and a private hiking trail.",
        location: "Barton Creek, Austin",
        type: "villa", rent: 7500, rentType: "monthly",
        bedrooms: 5, bathrooms: 4, size: 4900,
        amenities: A.villa,
        images: [pool.luxury[0], pool.luxury[2], pool.exterior[4]],
        extraFeatures: "Private hiking trail, entertainment pavilion",
        status: "approved",
    },
    {
        title: "Nashville Luxury Estate",
        description: "Grand 5-bedroom Nashville estate on 3 private acres. Saltwater pool, outdoor kitchen with pizza oven, game room, and a separate guest suite.",
        location: "Belle Meade, Nashville",
        type: "villa", rent: 9000, rentType: "monthly",
        bedrooms: 5, bathrooms: 5, size: 5500,
        amenities: ["Saltwater Pool", "Outdoor Kitchen", "Game Room", "Home Theater", "Security"],
        images: [pool.luxury[3], pool.luxury[1], pool.exterior[5]],
        extraFeatures: "3 private acres, saltwater pool",
        status: "approved",
    },
    {
        title: "Buckhead Luxury Villa",
        description: "Elegant 4-bedroom Atlanta villa in the exclusive Tuxedo Park enclave. Formal gardens, heated pool, chef's kitchen, and a dedicated wine room.",
        location: "Tuxedo Park, Atlanta",
        type: "villa", rent: 7200, rentType: "monthly",
        bedrooms: 4, bathrooms: 4, size: 4300,
        amenities: A.villa,
        images: [pool.luxury[2], pool.luxury[0], pool.exterior[6]],
        extraFeatures: "Formal gardens, wine room",
        status: "approved",
    },

    // ── STUDIOS (10) ─────────────────────────────────────────────────────────
    {
        title: "SoHo Artist Loft",
        description: "Dramatic SoHo loft with 14-foot ceilings, exposed brick, and cast-iron columns. Flooded with natural light — perfect for artists or creative professionals.",
        location: "SoHo, New York",
        type: "studio", rent: 2500, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 620,
        amenities: A.studio,
        images: [pool.interior[0], pool.interior[4], pool.interior[8]],
        extraFeatures: "14-ft ceilings, exposed brick",
        status: "approved",
    },
    {
        title: "Venice Beach Studio",
        description: "Bright studio steps from the Venice Beach boardwalk. Fully furnished with a queen bed, kitchenette, and a private patio. Surfboard storage available.",
        location: "Venice Beach, Los Angeles",
        type: "studio", rent: 2000, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 440,
        amenities: ["Wi-Fi", "Furnished", "Private Patio", "Air Conditioning"],
        images: [pool.interior[1], pool.interior[5], pool.interior[7]],
        extraFeatures: "Beach access, furnished, surfboard storage",
        status: "approved",
    },
    {
        title: "Wynwood Art Studio",
        description: "Creative studio in Miami's Wynwood arts district. High-polished concrete floors, industrial windows, and surrounded by world-class street art.",
        location: "Wynwood, Miami",
        type: "studio", rent: 1600, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 480,
        amenities: A.studio,
        images: [pool.interior[2], pool.interior[6], pool.interior[3]],
        extraFeatures: "Art district location, industrial design",
        status: "approved",
    },
    {
        title: "Wicker Park Sunny Studio",
        description: "Sunny studio in Chicago's vibrant Wicker Park. Exposed brick accent wall, updated kitchen with quartz counters, and steps from the Blue Line L train.",
        location: "Wicker Park, Chicago",
        type: "studio", rent: 1500, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 420,
        amenities: ["Wi-Fi", "Air Conditioning", "Laundry", "Storage"],
        images: [pool.interior[3], pool.interior[7], pool.interior[1]],
        extraFeatures: "Transit access, exposed brick",
        status: "approved",
    },
    {
        title: "Fremont Micro Studio",
        description: "Thoughtfully designed micro studio in Seattle's Fremont neighborhood. Clever built-in storage, Murphy bed, and a Juliet balcony with neighborhood views.",
        location: "Fremont, Seattle",
        type: "studio", rent: 1600, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 360,
        amenities: ["Wi-Fi", "Murphy Bed", "Juliet Balcony", "Utilities Included"],
        images: [pool.interior[4], pool.interior[0], pool.interior[6]],
        extraFeatures: "Murphy bed, utilities included",
        status: "approved",
    },
    {
        title: "Allston Student Studio",
        description: "Practical and cozy studio in Allston, Boston's best-value neighborhood. Close to Harvard Ave and the Green Line. Heat included in rent.",
        location: "Allston, Boston",
        type: "studio", rent: 1350, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 400,
        amenities: ["Wi-Fi", "Laundry", "Heat Included", "Elevator"],
        images: [pool.interior[5], pool.interior[2], pool.interior[8]],
        extraFeatures: "Heat included, T access nearby",
        status: "approved",
    },
    {
        title: "East Austin Creative Studio",
        description: "Hip studio in East Austin's creative corridor. Polished concrete floors, high ceilings, a private courtyard, and bike parking.",
        location: "East Austin, Texas",
        type: "studio", rent: 1300, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 450,
        amenities: ["Wi-Fi", "Private Courtyard", "Bike Parking", "Air Conditioning"],
        images: [pool.interior[6], pool.interior[3], pool.interior[0]],
        extraFeatures: "Private courtyard, creative neighborhood",
        status: "approved",
    },
    {
        title: "RiNo Artist Studio",
        description: "Inspiring studio in Denver's River North Art District. Polished concrete floors, oversized industrial windows, and surrounded by galleries and breweries.",
        location: "River North, Denver",
        type: "studio", rent: 1450, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 470,
        amenities: A.studio,
        images: [pool.interior[7], pool.interior[4], pool.interior[1]],
        extraFeatures: "Art district, brewery walkable",
        status: "approved",
    },
    {
        title: "SoBro Music Studio",
        description: "Cool fully furnished studio in Nashville's SoBro neighborhood, steps from Lower Broad and the best live music in the world.",
        location: "SoBro, Nashville",
        type: "studio", rent: 1700, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 490,
        amenities: ["Wi-Fi", "Furnished", "Air Conditioning", "Elevator"],
        images: [pool.interior[8], pool.interior[5], pool.interior[2]],
        extraFeatures: "Furnished, steps from live music",
        status: "approved",
    },
    {
        title: "Castleberry Hill Loft Studio",
        description: "Industrial loft studio in Atlanta's historic arts district. 12-foot ceilings, exposed ductwork, large street-facing windows, and in-unit laundry.",
        location: "Castleberry Hill, Atlanta",
        type: "studio", rent: 1550, rentType: "monthly",
        bedrooms: 1, bathrooms: 1, size: 530,
        amenities: ["Wi-Fi", "In-Unit Laundry", "Air Conditioning", "Bike Storage"],
        images: [pool.interior[0], pool.interior[7], pool.interior[4]],
        extraFeatures: "12-ft ceilings, art district",
        status: "approved",
    },

    // ── OFFICES (5) ──────────────────────────────────────────────────────────
    {
        title: "Midtown Manhattan Office Suite",
        description: "Premium 4,000 sq ft office suite in Midtown with 57th Street views. 15 private offices, 2 conference rooms, reception, and a full kitchen.",
        location: "Midtown, New York",
        type: "office", rent: 8000, rentType: "monthly",
        bedrooms: 0, bathrooms: 2, size: 4000,
        amenities: A.office,
        images: p3(pool.office),
        extraFeatures: "57th Street views, 2 conference rooms",
        status: "approved",
    },
    {
        title: "Downtown Seattle Tech Office",
        description: "Open-plan 2,500 sq ft tech-ready office in downtown Seattle. Exposed ceilings, collaborative zones, private phone booths, and rooftop breakout space.",
        location: "Downtown, Seattle",
        type: "office", rent: 4500, rentType: "monthly",
        bedrooms: 0, bathrooms: 2, size: 2500,
        amenities: ["High-Speed Internet", "Rooftop", "Phone Booths", "Bike Storage", "Showers"],
        images: [pool.office[0], pool.office[2], pool.interior[7]],
        extraFeatures: "Rooftop breakout, bike storage, showers",
        status: "approved",
    },
    {
        title: "Austin Domain Tech Hub",
        description: "Modern 1,800 sq ft office in the Domain, Austin's premier tech and shopping district. Glass conference room, standing desks, and fiber internet.",
        location: "The Domain, Austin",
        type: "office", rent: 3200, rentType: "monthly",
        bedrooms: 0, bathrooms: 1, size: 1800,
        amenities: A.office,
        images: [pool.office[1], pool.office[0], pool.interior[8]],
        extraFeatures: "Fiber internet, glass conference room",
        status: "approved",
    },
    {
        title: "Denver LoDo Creative Office",
        description: "Converted warehouse office in LoDo Denver with original brick, timber beams, and an industrial aesthetic. 2,200 sq ft with private patio access.",
        location: "LoDo, Denver",
        type: "office", rent: 3800, rentType: "monthly",
        bedrooms: 0, bathrooms: 2, size: 2200,
        amenities: ["High-Speed Internet", "Private Patio", "Parking", "Storage"],
        images: [pool.office[2], pool.office[0], pool.interior[6]],
        extraFeatures: "Exposed brick, private patio",
        status: "approved",
    },
    {
        title: "Chicago River North Office",
        description: "Boutique 1,500 sq ft office in Chicago's River North gallery district. Three private offices, polished concrete floors, and river views.",
        location: "River North, Chicago",
        type: "office", rent: 3500, rentType: "monthly",
        bedrooms: 0, bathrooms: 1, size: 1500,
        amenities: A.office,
        images: [pool.office[1], pool.office[2], pool.interior[5]],
        extraFeatures: "River views, fully furnished",
        status: "approved",
    },

    // ── SHOPS (3) ────────────────────────────────────────────────────────────
    {
        title: "SoHo Flagship Retail Space",
        description: "Prime ground-floor retail in SoHo, one of the world's most sought-after shopping corridors. 1,200 sq ft with 20-ft ceilings and floor-to-ceiling windows.",
        location: "SoHo, New York",
        type: "shop", rent: 9500, rentType: "monthly",
        bedrooms: 0, bathrooms: 1, size: 1200,
        amenities: A.shop,
        images: [pool.interior[0], pool.exterior[0], pool.office[0]],
        extraFeatures: "20-ft ceilings, high foot traffic",
        status: "approved",
    },
    {
        title: "Sunset Strip Boutique Space",
        description: "Iconic 900 sq ft retail or showroom space on the Sunset Strip. Floor-to-ceiling glass storefront, private parking, and excellent street visibility.",
        location: "Sunset Strip, Los Angeles",
        type: "shop", rent: 5800, rentType: "monthly",
        bedrooms: 0, bathrooms: 1, size: 900,
        amenities: ["Glass Storefront", "Private Parking", "Air Conditioning", "Storage"],
        images: [pool.interior[1], pool.exterior[1], pool.office[1]],
        extraFeatures: "Glass storefront, private parking",
        status: "approved",
    },
    {
        title: "Lincoln Road Corner Retail",
        description: "Premium corner retail on Lincoln Road, South Beach's premier pedestrian promenade. 1,100 sq ft with interior and exterior display areas and constant foot traffic.",
        location: "Lincoln Road, Miami Beach",
        type: "shop", rent: 6500, rentType: "monthly",
        bedrooms: 0, bathrooms: 1, size: 1100,
        amenities: A.shop,
        images: [pool.interior[2], pool.exterior[2], pool.office[2]],
        extraFeatures: "Corner location, exterior display area",
        status: "approved",
    },
];

async function main() {
    console.log("🌱 Connecting to MongoDB...");
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected");

    // Find an existing owner, or create a seed owner
    let owner = await User.findOne({ role: "owner" });
    if (!owner) {
        owner = await User.create({
            name: "UrbanNest Demo Owner",
            email: "demoowner@urbannest.com",
            photo: img("1633332755192-727a05c4013d"),
            role: "owner",
        });
        console.log("👤 Created seed owner:", owner.email);
    } else {
        console.log("👤 Using existing owner:", owner.email);
    }

    // Clear existing properties
    const { deletedCount } = await Property.deleteMany({});
    console.log(`🗑️  Cleared ${deletedCount} existing properties`);

    // Attach ownerId and insert
    const docs = seed.map((p) => ({ ...p, ownerId: owner._id }));
    const inserted = await Property.insertMany(docs);
    console.log(`✅ Seeded ${inserted.length} properties successfully`);

    await mongoose.disconnect();
    console.log("🔌 Done!");
}

main().catch((err) => {
    console.error("❌ Seed failed:", err.message);
    process.exit(1);
});